### ISSUE TITLE
Date handling

### ISSUE THREAD

**Issue by nolanamy** [tarunc/intercom.io#10]
I can safely use `Date` objects for standard user attributes:

```
intercom.createUser({
  ...,
  last_request_at: session.used
}, cb);
```

But for custom data I have to convert to an integer timestamp in seconds:

```
customData['Last used app'] = Math.round(session.used.getTime()/1000);
```

Using a `Date` in custom data gives a very old time in Intercom (perhaps Unix time 0), and using an integer timestamp in milliseconds gives a time far in the future.

Perhaps intercom.io should check for `Date` objects in custom data and automatically convert them to Intercom-friendly timestamps.

**Comment by tarunc** [comment]
I'm hesitant to do this since it assumes something about the data being given. Right now, this library doesn't go through any of the data given to it. It would be great if we included for validations for the data to make sure the data being passed in looks correct. Along with those checks, we could parse JavaScript dates automatically too. Right now, this library just returns intercom.io errors and lets intercom.io do the checking. I don't plan on making it go through the data being passed in to it because that would involve updating this library whenever intercom.io updates their API. However pull requests are accepted :)

There is an [intercom.date()](http://tarunc.github.io/intercom.io/#line-165) method that you can take a look at if you want an easy conversion of JavaScript dates to intercom.io dates.
