### ISSUE TITLE
missing data validity check for createUser() and updateUSer()

### ISSUE THREAD

**Issue by fabriziomoscon** [tarunc/intercom.io#8]
I was sending an object as `updateUser()` like so:
https://gist.github.com/fabriziomoscon/dc54598c5be16f28621e

and I was always getting server errors every now and then

from Intercom.io engeneer:

> ...
Based on the documentation of this library and my knowledge of our API, I can see a couple issues that could be causing the errors:
1. You need to send all custom data inside a hash; looks like everything below the email attribute in your gist needs to be nested in a custom_data hash.
2. We do not support arrays or hashes for custom data, so attributes like 'promocodes', 'promocodes_unsued', and 'operating_area' will cause errors.

Also the documentation has a reference on how to pass and validate `custom_attributes`
We should add some check to the function. So to help future users not to waste time like I did =)

**Comment by tarunc** [comment]
I'm hesitant to do this since it assumes something about the data being given. Right now, this library doesn't go through any of the data given to it. It would be great if we included validations for the data to make sure the data being passed in looks correct. Right now, this library just returns intercom.io errors and lets intercom.io do the checking. I don't plan on making it go through the data being passed in to it because that would involve updating this library whenever intercom.io updates their API. However pull requests are accepted :)
